/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ladyjane
 */
import java.awt.Color;
import javax.swing.ImageIcon;
import static javax.swing.JOptionPane.showMessageDialog;


public class NewJFrame extends javax.swing.JFrame {
    ImageIcon maleElfMage = new ImageIcon("pictures/maleElfMage.jpeg");
    ImageIcon maleElfBard = new ImageIcon("pictures/maleElfBard.jpeg");
    ImageIcon maleElfWarrior = new ImageIcon("pictures/maleElfWarrior.jpeg");
    ImageIcon maleOrcBard = new ImageIcon("pictures/maleOrcBard.jpeg");
    ImageIcon maleOrcWarrior = new ImageIcon("pictures/maleOrcWarrior.jpeg");
    ImageIcon maleOrcMage = new ImageIcon("pictures/maleOrcMage.jpeg");
    ImageIcon maleDwarfWarrior = new ImageIcon("pictures/maleDwarfWarrior.jpeg");
    ImageIcon maleDwarfMage = new ImageIcon("pictures/maleDwarfMage.jpeg");
    ImageIcon maleDwarfBard = new ImageIcon("pictures/maleDwarfBard.jpeg");
    ImageIcon femaleElfMage = new ImageIcon("pictures/femaleElfMage.jpeg");
    ImageIcon femaleElfBard = new ImageIcon("pictures/femaleElfBard.jpeg");
    ImageIcon femaleElfWarrior = new ImageIcon("pictures/femaleElfWarrior.jpeg");
    ImageIcon femaleOrcBard = new ImageIcon("pictures/femaleOrcBard.jpeg");
    ImageIcon femaleOrcWarrior = new ImageIcon("pictures/femaleOrcWarrior.jpeg");
    ImageIcon femaleOrcMage = new ImageIcon("pictures/femaleOrcMage.jpeg");
    ImageIcon femaleDwarfWarrior = new ImageIcon("pictures/femaleDwarfWarrior.jpeg");
    ImageIcon femaleDwarfMage = new ImageIcon("pictures/femaleDwarfMage.jpeg");
    ImageIcon femaleDwarfBard = new ImageIcon("pictures/femaleDwarfBard.jpeg");
    
    
    
    
 
    public NewJFrame() {
        initComponents();
        
        Color col=new Color(245,235,216);
        getContentPane().setBackground(col);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rasaComboBox = new javax.swing.JComboBox<>();
        povolaniComboBox = new javax.swing.JComboBox<>();
        jmenoInput = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        muzButton = new javax.swing.JRadioButton();
        zenaButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        labelPic = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("backgroundColor");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(153, 255, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        rasaComboBox.setFont(new java.awt.Font("URW Palladio L", 2, 24)); // NOI18N
        rasaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"elf", "trpaslík", "ork"}));
        rasaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rasaComboBoxActionPerformed(evt);
            }
        });

        povolaniComboBox.setFont(new java.awt.Font("URW Palladio L", 2, 24)); // NOI18N
        povolaniComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mág", "válečník", "bard"}));

        jmenoInput.setFont(new java.awt.Font("URW Palladio L", 2, 24)); // NOI18N

        jButton1.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        jButton1.setText("Vytvořit postavu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        jLabel1.setText("Jméno");

        jLabel2.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        jLabel2.setText("Rasa");

        jLabel3.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        jLabel3.setText("Povolání");

        muzButton.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        muzButton.setText("muž");
        muzButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muzButtonActionPerformed(evt);
            }
        });

        zenaButton.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        zenaButton.setText("žena");
        zenaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zenaButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("URW Palladio L", 2, 24)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        labelPic.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setFont(new java.awt.Font("URW Palladio L", 3, 36)); // NOI18N
        jLabel4.setText("Generátor fantasy postav");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(jmenoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(zenaButton)
                    .addComponent(muzButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rasaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(34, 34, 34)
                            .addComponent(povolaniComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(labelPic, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jmenoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(muzButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zenaButton)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(rasaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(povolaniComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(jButton1))
                    .addComponent(labelPic, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(895, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rasaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rasaComboBoxActionPerformed

    }//GEN-LAST:event_rasaComboBoxActionPerformed

    private static boolean isFullname(String str) {
    String expression = "^[A-ZÁČĎÉĚÍŇÓŘŠŤŮÚÝŽ][a-ž]+"; 
    return str.matches(expression);        
    }
    
    @SuppressWarnings("SuspiciousIndentAfterControlStatement")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String jmeno = jmenoInput.getText();
        if (jmeno.isEmpty()){
            showMessageDialog(null, "Jméno musí být vyplněno.");
            return;
        } 
        
        if (isFullname(jmeno) != true){
            showMessageDialog(null, "Jméno musí začínat na velké písmeno, nesmí obsahovat čísla, mezery a speciální znaky.");
            return;
        } 
        
        if (muzButton.isSelected()== false && zenaButton.isSelected()== false){
            showMessageDialog(null, "Pohlaví musí musí být vybráno.");
            return;
        }
        
        if (muzButton.isSelected() && rasaComboBox.getSelectedItem() == "elf" && povolaniComboBox.getSelectedItem() == "mág"){
            jTextArea1.setText(" Mé jméno je "+ jmeno + "."+ "\n" + " Jsem elf mág, mistr magie a strážce tajemství. \n Narodil jsem se do světa plného kouzel a zázraků a od útlého věku jsem se učil umění magie a kouzelnictví. \n Cestoval jsem po celém elfském království a hledal jsem starobylé znalosti a mocné artefakty. \n Jsem oslavován jako mocný čaroděj a můj talent je uznávaný všemi elfy.");
            labelPic.setIcon(maleElfMage);}
            
        if (muzButton.isSelected() && rasaComboBox.getSelectedItem() == "elf" && povolaniComboBox.getSelectedItem() == "bard"){
            jTextArea1.setText(" Mé jméno je "+ jmeno + "."+ "\n" + " Jsem elf bard, pěvec příběhů a mistr hudby. \n Narodil jsem se do světa plného krásy a magie a od útlého věku jsem se učil umění hudby a poezie. \n Cestoval jsem po celém elfském království a šířil jsem radost a inspiraci svými písněmi a příběhy. \n Jsem oslavován jako umělec a můj talent je uznávaný všemi elfy.");
            labelPic.setIcon(maleElfBard);}
        
        if (muzButton.isSelected() && rasaComboBox.getSelectedItem() == "elf" && povolaniComboBox.getSelectedItem() == "válečník"){
            jTextArea1.setText(" Mé jméno je "+ jmeno + "."+ "\n" + " Jsem elf válečník, ochránce elfského lidu a bojovník za spravedlnost. \n Narodil jsem se do světa plného konfliktů a od útlého věku jsem se cvičil v boji,\n abych mohl chránit svůj lid před nepřáteli.\n Bojoval jsem v mnoha bitvách a vždy jsem zvítězil. \n Jsem oslavován jako hrdina a mé příběhy se vyprávějí po celém elfském království.");
            labelPic.setIcon(maleElfWarrior);}
        
        
        if (zenaButton.isSelected() && rasaComboBox.getSelectedItem() == "elf" && povolaniComboBox.getSelectedItem() == "mág"){
            jTextArea1.setText(" Mé jméno je "+ jmeno + "."+ "\n" + " Jsem elfka mágyně, mistryně magie a strážkyně tajemství. \n Narodila jsem se do světa plného kouzel a zázraků a od útlého věku jsem se učila umění magie a kouzelnictví. \n Cestovala jsem po celém elfském království a hledala jsem starobylé znalosti a mocné artefakty. \n Jsem oslavována jako mocná čarodějka a můj talent je uznávaný všemi elfy.");
            labelPic.setIcon(femaleElfMage);}
            
        if (zenaButton.isSelected() && rasaComboBox.getSelectedItem() == "elf" && povolaniComboBox.getSelectedItem() == "bard"){
            jTextArea1.setText(" Mé jméno je "+ jmeno + "."+ "\n" + " Jsem elfka bardka, pěvkyně příběhů a mistryně hudby. \n Narodila jsem se do světa plného krásy a magie a od útlého věku jsem se učila umění hudby a poezie. \n Cestovala jsem po celém elfském království a šířila jsem radost a inspiraci svými písněmi a příběhy. \n Jsem oslavována jako umělkyně a můj talent je uznávaný všemi elfy.");
            labelPic.setIcon(femaleElfBard);}
        
        if (zenaButton.isSelected() && rasaComboBox.getSelectedItem() == "elf" && povolaniComboBox.getSelectedItem() == "válečník"){
            jTextArea1.setText(" Mé jméno je "+ jmeno + "."+ "\n" + " Jsem elfka válečnice, ochránkyně elfského lidu a bojovnice za spravedlnost. \n Narodila jsem se do světa plného konfliktů a od útlého věku jsem se cvičila v boji,\n abych mohla chránit svůj lid před nepřáteli.\n Bojovala jsem v mnoha bitvách a vždy jsem zvítězila. \n Jsem oslavována jako hrdinka a mé příběhy se vyprávějí po celém elfském království.");
            labelPic.setIcon(femaleElfWarrior);}
        
        
        if (muzButton.isSelected() && rasaComboBox.getSelectedItem() == "ork" && povolaniComboBox.getSelectedItem() == "mág"){
            jTextArea1.setText(" Mé jméno je "+ jmeno + "."+ "\n" + " Jsem ork mág, mistr magie a strážce tajemství. \n Narodil jsem se do světa plného kouzel a zázraků a od útlého věku jsem se učil umění magie a kouzelnictví. \n Cestoval jsem po celé orkské říši a hledal jsem starobylé znalosti a mocné artefakty. \n Jsem oslavován jako mocný čaroděj a můj talent je uznávaný všemi orky.");
            labelPic.setIcon(maleOrcMage);}
            
        if (muzButton.isSelected() && rasaComboBox.getSelectedItem() == "ork" && povolaniComboBox.getSelectedItem() == "bard"){
            jTextArea1.setText(" Mé jméno je "+ jmeno + "."+ "\n" + " Jsem ork bard, pěvec příběhů a mistr hudby. \n Narodil jsem se do světa plného krásy a magie a od útlého věku jsem se učil umění hudby a poezie. \n Cestoval jsem po celé orkské říši a šířil jsem radost a inspiraci svými písněmi a příběhy. \n Jsem oslavován jako umělec a můj talent je uznávaný všemi orky.");
            labelPic.setIcon(maleOrcBard);}
        
        if (muzButton.isSelected() && rasaComboBox.getSelectedItem() == "ork" && povolaniComboBox.getSelectedItem() == "válečník"){
            jTextArea1.setText(" Mé jméno je "+ jmeno + "."+ "\n" + " Jsem ork válečník, ochránce orkského lidu a bojovník za spravedlnost. \n Narodil jsem se do světa plného konfliktů a od útlého věku jsem se cvičil v boji,\n abych mohl chránit svůj lid před nepřáteli.\n Bojoval jsem v mnoha bitvách a vždy jsem zvítězil. \n Jsem oslavován jako hrdina a mé příběhy se vyprávějí po celé orkské říši.");
            labelPic.setIcon(maleOrcWarrior);}
        
        
        if (zenaButton.isSelected() && rasaComboBox.getSelectedItem() == "ork" && povolaniComboBox.getSelectedItem() == "mág"){
            jTextArea1.setText(" Mé jméno je "+ jmeno + "."+ "\n" + " Jsem orkyně mágyně, mistryně magie a strážkyně tajemství. \n Narodila jsem se do světa plného kouzel a zázraků a od útlého věku jsem se učila umění magie a kouzelnictví. \n Cestovala jsem po celé orkské říši a hledala jsem starobylé znalosti a mocné artefakty. \n Jsem oslavována jako mocná čarodějka a můj talent je uznávaný všemi orky.");
            labelPic.setIcon(femaleOrcMage);}
            
        if (zenaButton.isSelected() && rasaComboBox.getSelectedItem() == "ork" && povolaniComboBox.getSelectedItem() == "bard"){
            jTextArea1.setText(" Mé jméno je "+ jmeno + "."+ "\n" + " Jsem orkyně bardka, pěvkyně příběhů a mistryně hudby. \n Narodila jsem se do světa plného krásy a magie a od útlého věku jsem se učila umění hudby a poezie. \n Cestovala jsem po celé orkské říši a šířila jsem radost a inspiraci svými písněmi a příběhy. \n Jsem oslavována jako umělkyně a můj talent je uznávaný všemi orky.");
            labelPic.setIcon(femaleOrcBard);}
        
        if (zenaButton.isSelected() && rasaComboBox.getSelectedItem() == "ork" && povolaniComboBox.getSelectedItem() == "válečník"){
            jTextArea1.setText(" Mé jméno je "+ jmeno + "."+ "\n" + " Jsem orkyně válečnice, ochránkyně orkského lidu a bojovnice za spravedlnost. \n Narodila jsem se do světa plného konfliktů a od útlého věku jsem se cvičila v boji,\n abych mohla chránit svůj lid před nepřáteli.\n Bojovala jsem v mnoha bitvách a vždy jsem zvítězila. \n Jsem oslavována jako hrdinka a mé příběhy se vyprávějí po celé orkské říši.");
            labelPic.setIcon(femaleOrcWarrior);}
        
        
        if (muzButton.isSelected() && rasaComboBox.getSelectedItem() == "trpaslík" && povolaniComboBox.getSelectedItem() == "mág"){
            jTextArea1.setText(" Mé jméno je "+ jmeno + "."+ "\n" + " Jsem trpaslík mág, mistr magie a strážce tajemství. \n Narodil jsem se do světa plného kouzel a zázraků a od útlého věku jsem se učil umění magie a kouzelnictví. \n Cestoval jsem po celé trpasličí říši a hledal jsem starobylé znalosti a mocné artefakty. \n Jsem oslavován jako mocný čaroděj a můj talent je uznávaný všemi trpaslíky.");
            labelPic.setIcon(maleDwarfMage);}
            
        if (muzButton.isSelected() && rasaComboBox.getSelectedItem() == "trpaslík" && povolaniComboBox.getSelectedItem() == "bard"){
            jTextArea1.setText(" Mé jméno je "+ jmeno + "."+ "\n" + " Jsem trpaslík bard, pěvec příběhů a mistr hudby. \n Narodil jsem se do světa plného krásy a magie a od útlého věku jsem se učil umění hudby a poezie. \n Cestoval jsem po celé trpasličí říši a šířil jsem radost a inspiraci svými písněmi a příběhy. \n Jsem oslavován jako umělec a můj talent je uznávaný všemi trpaslíky.");
            labelPic.setIcon(maleDwarfBard);}
        
        if (muzButton.isSelected() && rasaComboBox.getSelectedItem() == "trpaslík" && povolaniComboBox.getSelectedItem() == "válečník"){
            jTextArea1.setText(" Mé jméno je "+ jmeno + "."+ "\n" + " Jsem trpaslík válečník, ochránce trpasličího lidu a bojovník za spravedlnost. \n Narodil jsem se do světa plného konfliktů a od útlého věku jsem se cvičil v boji,\n abych mohl chránit svůj lid před nepřáteli.\n Bojoval jsem v mnoha bitvách a vždy jsem zvítězil. \n Jsem oslavován jako hrdina a mé příběhy se vyprávějí po celé trpasličí říši.");
            labelPic.setIcon(maleDwarfWarrior);}
        
        
        if (zenaButton.isSelected() && rasaComboBox.getSelectedItem() == "trpaslík" && povolaniComboBox.getSelectedItem() == "mág"){
            jTextArea1.setText(" Mé jméno je "+ jmeno + "."+ "\n" + " Jsem trpaslice mágyně, mistryně magie a strážkyně tajemství. \n Narodila jsem se do světa plného kouzel a zázraků a od útlého věku jsem se učila umění magie a kouzelnictví. \n Cestovala jsem po celé trpasličí říši a hledala jsem starobylé znalosti a mocné artefakty. \n Jsem oslavována jako mocná čarodějka a můj talent je uznávaný všemi trpaslíky.");
            labelPic.setIcon(femaleDwarfMage);}
            
        if (zenaButton.isSelected() && rasaComboBox.getSelectedItem() == "trpaslík" && povolaniComboBox.getSelectedItem() == "bard"){
            jTextArea1.setText(" Mé jméno je "+ jmeno + "."+ "\n" + " Jsem trpaslice bardka, pěvkyně příběhů a mistryně hudby. \n Narodila jsem se do světa plného krásy a magie a od útlého věku jsem se učila umění hudby a poezie. \n Cestovala jsem po celé trpasličí říši a šířila jsem radost a inspiraci svými písněmi a příběhy. \n Jsem oslavována jako umělkyně a můj talent je uznávaný všemi trpaslíky.");
            labelPic.setIcon(femaleDwarfBard);}
        
        if (zenaButton.isSelected() && rasaComboBox.getSelectedItem() == "trpaslík" && povolaniComboBox.getSelectedItem() == "válečník"){
            jTextArea1.setText(" Mé jméno je "+ jmeno + "."+ "\n" + " Jsem trpaslice válečnice, ochránkyně trpasličího lidu a bojovnice za spravedlnost. \n Narodila jsem se do světa plného konfliktů a od útlého věku jsem se cvičila v boji,\n abych mohla chránit svůj lid před nepřáteli.\n Bojovala jsem v mnoha bitvách a vždy jsem zvítězila. \n Jsem oslavována jako hrdinka a mé příběhy se vyprávějí po celé trpasličí říši.");
            labelPic.setIcon(femaleDwarfWarrior);}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void zenaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zenaButtonActionPerformed
        // TODO add your handling code here:
        if (zenaButton.isSelected())
            muzButton.setSelected(false);
    }//GEN-LAST:event_zenaButtonActionPerformed

    private void muzButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muzButtonActionPerformed
        // TODO add your handling code here:
        if (muzButton.isSelected())
            zenaButton.setSelected(false);
    }//GEN-LAST:event_muzButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jmenoInput;
    private javax.swing.JLabel labelPic;
    private javax.swing.JRadioButton muzButton;
    private javax.swing.JComboBox<String> povolaniComboBox;
    private javax.swing.JComboBox<String> rasaComboBox;
    private javax.swing.JRadioButton zenaButton;
    // End of variables declaration//GEN-END:variables
}
